system.debug(
    JSON.serializePretty(
      FieloELR.ModuleService.getModuleResponse(
        'a0l6A000000pxLeQAI',
        new Set<String> {'Name','FieloELR__Module__r.FieloELR__Course__c'},
        new Set<String> {'Name','FieloELR__Type__c','FieloELR__Module__r.FieloELR__Course__c'},
        new Set<String> {'FieloELR__Question__c','FieloELR__AnswerOptionText__c','FieloELR__MatchingText__c'}
    )
  )
);
