@isTest
public class TestUpdateAnswersBatchSchedule {
	@isTest static void runTests() {
		FieloELRUPD_MockUpFactory.testTemporal();
		FieloELRUPD_MockUpFactory.testTemporal2();
		FieloELRUPD_MockUpFactory.testTemporal3();
		FieloELRUPD_MockUpFactory.testTemporal4();
		FieloELRUPD_MockUpFactory.testTemporal5();
		FieloELRUPD_MockUpFactory.testTemporal6();
		FieloELRUPD_MockUpFactory.testTemporal7();
		FieloELRUPD_MockUpFactory.testTemporal8();
		FieloELRUPD_MockUpFactory.testTemporal9();
		FieloELRUPD_MockUpFactory.testTemporal10();
		FieloELRUPD_MockUpFactory.testTemporal11();
		FieloELRUPD_MockUpFactory.testTemporal12();
		FieloELRUPD_MockUpFactory.testTemporal13();
		FieloELRUPD_MockUpFactory.testTemporal14();
		FieloELRUPD_MockUpFactory.testTemporal15();
		FieloELRUPD_MockUpFactory.testTemporal16();
		FieloELRUPD_MockUpFactory.testTemporal17();
		FieloELRUPD_MockUpFactory.testTemporal18();
	}
}