@isTest
public class TestUpdateAnswersBatchSchedule {
	@isTest static void runTests() {
		MockUpFactory.testTemporal();
		MockUpFactory.testTemporal2();
		MockUpFactory.testTemporal3();
		MockUpFactory.testTemporal4();
		MockUpFactory.testTemporal5();
		MockUpFactory.testTemporal6();
		MockUpFactory.testTemporal7();
		MockUpFactory.testTemporal8();
		MockUpFactory.testTemporal9();
		MockUpFactory.testTemporal10();
		MockUpFactory.testTemporal11();
		MockUpFactory.testTemporal12();
		MockUpFactory.testTemporal13();
		MockUpFactory.testTemporal14();
		MockUpFactory.testTemporal15();
		MockUpFactory.testTemporal16();
		MockUpFactory.testTemporal17();
		MockUpFactory.testTemporal18();
	}
}